version: '2'

services:

  node:
    image: mhart/alpine-node:6
    depends_on:
      - mysql
      - rethinkdb
      - rabbitmq
      - logstash
      - elasticsearch
    command: node --version

  mysql:
    image: library/mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: none

  rethinkdb:
    image: library/rethinkdb
    ports:
      - "28080:8080"
      - "28015:28015"
      - "29015:29015"

  rabbitmq:
    image: tutum/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_PASS: none

  logstash:
    build: docker/logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"

  elasticsearch:
    build: docker/elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
