version: '2'

services:
  node:
    image: mhart/alpine-node:6
    container_name: deve_node
    depends_on:
      - mysql
      - rethinkdb
      - rabbitmq
      - logstash
      - elasticsearch
    command: node --version
  mysql:
    image: library/mysql:5
    container_name: deve_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: none
  rethinkdb:
    image: library/rethinkdb
    container_name: deve_rethinkdb
    ports:
      - "28080:8080"
      - "28015:28015"
      - "29015:29015"
  rabbitmq:
    image: tutum/rabbitmq:latest
    container_name: deve_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_PASS: none
  logstash:
    build: docker/logstash/
    container_name: deve_logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
  elasticsearch:
    build: docker/elasticsearch/
    container_name: deve_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
