'use strict'

var nconf = require('nconf')
nconf.argv().env().file({ file: 'nconf-deve.json' })

var options = {
  // server
  ABIBAO_API_GATEWAY_ENV: nconf.get('ABIBAO_API_GATEWAY_ENV') || 'deve',
  ABIBAO_API_GATEWAY_URI: nconf.get('ABIBAO_API_GATEWAY_URI') || 'http://api.abibao.local.network.net:7000',
  ABIBAO_API_GATEWAY_EXPOSE_HOST: nconf.get('ABIBAO_API_GATEWAY_EXPOSE_HOST') || '0.0.0.0',
  ABIBAO_API_GATEWAY_EXPOSE_PORT: nconf.get('ABIBAO_API_GATEWAY_EXPOSE_PORT') || 7000,
  ABIBAO_API_GATEWAY_CRYPTO_CREDENTIALS: nconf.get('ABIBAO_API_GATEWAY_CRYPTO_CREDENTIALS') || 'this is my secret',
  // logs
  ABIBAO_API_GATEWAY_SLACK_WEBHOOK: nconf.get('ABIBAO_API_GATEWAY_SLACK_WEBHOOK') || 'http://localhost',
  ABIBAO_API_GATEWAY_LOGSTASH_HOST: nconf.get('ABIBAO_API_GATEWAY_LOGSTASH_HOST') || 'localhost',
  ABIBAO_API_GATEWAY_LOGSTASH_PORT: nconf.get('ABIBAO_API_GATEWAY_LOGSTASH_PORT') || 5000,
  ABIBAO_API_GATEWAY_NEWRELIC_APPNAME: nconf.get('ABIBAO_API_GATEWAY_NEWRELIC_APPNAME') || 'api.deve.abibao.com',
  // databases: rethinkdb
  ABIBAO_API_GATEWAY_RETHINKDB_HOST: nconf.get('ABIBAO_API_GATEWAY_RETHINKDB_HOST') || 'localhost',
  ABIBAO_API_GATEWAY_RETHINKDB_PORT: nconf.get('ABIBAO_API_GATEWAY_RETHINKDB_PORT') || 28015,
  ABIBAO_API_GATEWAY_RETHINKDB_USER: nconf.get('ABIBAO_API_GATEWAY_RETHINKDB_USER') || 'admin',
  ABIBAO_API_GATEWAY_RETHINKDB_PASS: nconf.get('ABIBAO_API_GATEWAY_RETHINKDB_PASS') || 'admin',
  ABIBAO_API_GATEWAY_RETHINKDB_DATABASE: nconf.get('ABIBAO_API_GATEWAY_RETHINKDB_DATABASE') || 'devemvp',
  // databases: postgres
  ABIBAO_API_GATEWAY_POSTGRES_HOST: nconf.get('ABIBAO_API_GATEWAY_POSTGRES_HOST') || 'localhost',
  ABIBAO_API_GATEWAY_POSTGRES_PORT: nconf.get('ABIBAO_API_GATEWAY_POSTGRES_PORT') || 5432,
  ABIBAO_API_GATEWAY_POSTGRES_USER: nconf.get('ABIBAO_API_GATEWAY_POSTGRES_USER') || 'infra',
  ABIBAO_API_GATEWAY_POSTGRES_PASS: nconf.get('ABIBAO_API_GATEWAY_POSTGRES_PASS') || 'infra',
  ABIBAO_API_GATEWAY_POSTGRES_DATABASE: nconf.get('ABIBAO_API_GATEWAY_POSTGRES_DATABASE') || 'devemvp',
  // rabbitmq
  ABIBAO_API_GATEWAY_RABBITMQ_HOST: nconf.get('ABIBAO_API_GATEWAY_RABBITMQ_HOST') || 'localhost',
  ABIBAO_API_GATEWAY_RABBITMQ_PORT: nconf.get('ABIBAO_API_GATEWAY_RABBITMQ_PORT') || 5672,
  ABIBAO_API_GATEWAY_RABBITMQ_USER: nconf.get('ABIBAO_API_GATEWAY_RABBITMQ_USER') || 'infra',
  ABIBAO_API_GATEWAY_RABBITMQ_PASS: nconf.get('ABIBAO_API_GATEWAY_RABBITMQ_PASS') || 'infra',
  // sendgrid
  ABIBAO_API_GATEWAY_SENDGRID_API_KEY: nconf.get('ABIBAO_API_GATEWAY_SENDGRID_API_KEY') || 'this is a sendgrid api key',
  ABIBAO_API_GATEWAY_SENDGRID_TEMPLATE_ABIBAO_AFFECT_CAMPAIGNS_AUTO: nconf.get('ABIBAO_API_GATEWAY_SENDGRID_TEMPLATE_ABIBAO_AFFECT_CAMPAIGNS_AUTO') || 'sendgrid template 01',
  ABIBAO_API_GATEWAY_SENDGRID_TEMPLATE_INDIVIDUAL_AFFECT_CAMPAIGNS_AUTO: nconf.get('ABIBAO_API_GATEWAY_SENDGRID_TEMPLATE_INDIVIDUAL_AFFECT_CAMPAIGNS_AUTO') || 'sendgrid template 02',
  // module: dashboard
  ABIBAO_WEB_DASHBOARD_URI: nconf.get('ABIBAO_WEB_DASHBOARD_URI') || 'http://api.abibao.local.network.net:7070',
  // module: wordpress SMF
  ABIBAO_API_GATEWAY_WPSMF_URI: nconf.get('ABIBAO_API_GATEWAY_WPSMF_URI') || 'http://localhost',
  ABIBAO_API_GATEWAY_WPSMF_AUTH_BASIC_USER: nconf.get('ABIBAO_API_GATEWAY_WPSMF_AUTH_BASIC_USER') || 'infra',
  ABIBAO_API_GATEWAY_WPSMF_AUTH_BASIC_PASS: nconf.get('ABIBAO_API_GATEWAY_WPSMF_AUTH_BASIC_PASS') || 'infra'
}

module.exports = function (key) {
  return options[key]
}
