"use strict";

module.exports = {
  
  EVENT_CAMPAIGN_PUBLISHED: 'EVENT_CAMPAIGN_PUBLISHED',
  EVENT_INDIVIDUAL_UPDATED: 'EVENT_INDIVIDUAL_UPDATED',
  EVENT_INDIVIDUAL_CREATED: 'EVENT_INDIVIDUAL_CREATED',
  EVENT_ENTITY_UPDATED: 'EVENT_ENTITY_UPDATED',
  EVENT_ENTITY_CREATED: 'EVENT_ENTITY_CREATED',
  EVENT_SURVEY_CREATED: 'EVENT_SURVEY_CREATED',
  EVENT_SURVEY_UPDATED: 'EVENT_SURVEY_UPDATED',
  
  connectionHandler: function(socket) {
    socket.server.logger.info('SocketIO connection established', socket.id);
  }
};